---
title: "DyHead performance eval"
author: "Chris Kennedy"
date: "2024-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(remotes)
library(dplyr)
library(nanoparquet)
```


## Import data


```{r dyhead_perf}
df = rio::import("tables/dyhead-frame-predictions.xlsx")
str(df)

# Load labels
# Generated by video.ipynb
label_df = rio::import("data/gpt-video-probabilites.parquet")
str(label_df)

table(label_df$theme)
```

## Integrate

```{r integrate}
df2 = df %>%
  group_by(video) %>%
  summarize(mod = max(mod),
            pod = max(pod)) %>%
  mutate(vaping_prob = pmax(mod, pod),
         vaping_pred_label = as.integer(vaping_prob > 0.774))

str(df2)

df3 = merge(df2, label_df %>% select(path:video), by = "video")

str(df3)

# AUC = 0.571, (0.314 - 0.828)
ck37r:::auc_inference(df3$vaping_prob, as.integer(df3$theme == "ecigs"))

acc_df = data.frame(vaping_prob = df3 %>% arrange(vaping_prob) %>% pull(vaping_prob) %>% unique(),
                    accuracy = NA)

dim(acc_df)

for (row_i in seq(nrow(acc_df))) {
  prob_i = acc_df[row_i, "vaping_prob"]
  
  acc_i = mean((df3$vaping_prob >= prob_i) == (df3$theme == "ecigs"))
  acc_df[row_i, "accuracy"] = acc_i
}

acc_df

summary(acc_df)
library(ggplot2)
ggplot(acc_df, aes(x = vaping_prob, y = accuracy)) +
  geom_point() + theme_minimal()


# 79.4% accuracy
mean(df3$vaping_pred_label == (df3$theme == "ecigs"))
mean(df3$theme == "ecigs")

```

## Other way

```{r other_way}
df4 = merge(df, label_df %>% select(path:video), by = "video")

str(df4)

library(data.table)
setDT(df4)
df4[theme == "ecigs", .(video, mod, pod, max_mod_pod = pmax(mod, pod))]
df4[theme == "ecigs", .(video, max_mod_pod = pmax(mod, pod))]
df4[theme == "ecigs", .(video, max_mod_pod = max(mod, pod)), by = video]
df4[, .(is_ecig = as.integer(theme == "ecigs"), video, max_mod_pod = max(mod, pod)), by = video]
```
